### ISSUE TITLE
Brand and toggle block ToC

### ISSUE THREAD

**Issue by bryanibit** [allejo/jekyll-toc#19]
First of all, I need to say that I am totally a novice for web designing.

**Description**

That is my [blog](bryanibit.github.io).  For better mobile display, I add brand and toggle shown in the [link](https://drive.google.com/file/d/1iaTlecJceJUZ83fstJX6fIZf66IgUes6/view?usp=sharing). As you can see, the ToC is blocked by toggle whose code is shown [here](https://github.com/bryanibit/bryanibit.github.io/blob/master/_includes/nav.html)

**Expected TOC**

I wish ToC could move several spaces downwards. I will it could add a new feature to the ToC. That would be wonderful.

Thank you so much!

**Comment by allejo** [comment]
Hi there bryanibit!

So this isn't a bug with how this TOC generator works nor would it be a feature. The problem you're facing is due to CSS.

Your nav has a class of `navbar-fixed-top` which means it will be fixed to the top of the screen meaning it no longer will interact with other DOM elements. The simplest fix would be to add padding-top to `intro-header` the same height as your navigation bar and that'll push down your TOC.

I'm going to close this issue since it's not related to the TOC's functionality. I'm happy to help, but this isn't the place for CSS support; for that, I'd recommend Stack Overflow.
