### ISSUE TITLE
Skipping non-markdown headers

### ISSUE THREAD

**Issue by jcornelius** [allejo/jekyll-toc#32]
**Description**
When you have a `.md` file which contains raw HTML headers, the current implementation will add those headers to the navigation, which isn't always desired. There should be a way to exclude any raw HTML headers from the TOC.

**Sample Usage**

Kramdown offers the ability to automatically add `id="..."` attributes to the headers it generates using `auto_ids: true`. Combining this with the following code skips the raw HTML headers (unless they also contain `id="..."`).

Adding the following at line 43 of [TOC.html](https://github.com/allejo/jekyll-toc/blob/master/_includes/toc.html) to achieve this result.
```twig
{% unless node contains "id=" %}
  {% continue %}
{% endunless %}
```

**Comment by allejo** [comment]
I've been thinking about this one for a bit. While I like the idea of skipping headings without IDs, I don't think that's the right behavior. Thinking about this semantically, a heading without an ID still makes for a valid document; there just happens to be no way to link to it.

So I've opened #33 that will instead render the content of the headings as plain text instead of a link. This way, the TOC will still represent the document structure.

If you need to skip headings from a TOC, there's always adding `.no_toc` as a class to the heading.

What are your thoughts?

**Comment by jcornelius** [comment]
Consider a case where you are building a documentation site (like getbootstrap.com) and you are providing example markup for various components which include headings. You don't want the headings used in the examples to be included in the TOC, and you don't want to include `.no_toc` in the example code either. How would you solve for this?

**Comment by allejo** [comment]
I hadn't thought about that using it that way; I like it :+1:

I think I'll still implement #33 as a fix for broken headers and then add an opt-in parameter, `skipNoIDs`?

**Comment by allejo** [comment]
Alrighty @jcornelius I committed 0c894b3c546ea83f798382853f74263b1f45d750 that adds the new opt-in behavior. Wanna give PR #33 a try?
