### ISSUE TITLE
No Effect in Github Pages Theme

### ISSUE THREAD

**Issue by dgjansen** [allejo/jekyll-toc#7]
I've followed the instructions at
https://allejo.io/blog/a-jekyll-toc-without-plugins-or-javascript/
and compared with
https://github.com/ministryofjustice/technical-guidance/pull/7
so I've added the include in:
https://github.com/dgjansen/Lizenzcenter/Cases.md
and I've added the toc.html in
https://github.com/dgjansen/Lizenzcenter/tree/master/_includes
but it seems **nothing happens** at all.

I'm trying to use it here:
https://dgjansen.github.io/Lizenzcenter/Cases

But somehow it's not working. Nothing happens. Any ideas?

Could it be it's not compatible with the default github pages templates?

**Comment by allejo** [comment]
This project *should* work anywhere, including Jekyll themes. However, this project is designed to be used inside Jekyll layouts, not markdown documents. If you look at the UK's usage, you'll see that it's in `_layout/default.html`. In order for it to work with GitHub themes, you'll have to [override the layouts provided by the theme](https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/) and include `toc.html` in your overridden layout.

Since you're using the "Slate" theme, this is the file you'll have to copy paste into your repository and then you'd be able to use `toc.html`.

https://github.com/pages-themes/slate/blob/master/_layouts/default.html

**Comment by dgjansen** [comment]
Thanks a lot! I've got it to work.

**Comment by allejo** [comment]
glad to hear! 👍
