### ISSUE TITLE
release jekyll-toc as a gem on rubygems.org

### ISSUE THREAD

**Issue by m5o** [allejo/jekyll-toc#9]
Hey @allejo 👋 

What do you think about releasing your work as a gem on [rubygems.org](https://rubygems.org) so it can easily integrated with any jekyll application?

✨ 💎 ✨ 

/m5o

**Comment by allejo** [comment]
Oh sup @m5o, been a while 👋 

As a novice to the Ruby ecosystem. How would a gem even be built for a snippet like this? I'm familiar with Jekyll themes/plugins and building gems for that, but how would a gem for a single Jekyll include work?

I'd still distribute just the HTML file for people to include manually on GH pages (since GH compatibility is the reason for this project) but I'm open to the idea of distributing it as a gem if it's possible.

**Comment by m5o** [comment]
On https://pages.github.com/versions/ is a list with all plugins integrated to GH pages. Maybe useful as inspiration. I also don't know in detail but maybe some pro's like @benbalter would help out with a advice.

**Comment by allejo** [comment]
> On pages.github.com/versions is a list with all plugins integrated to GH pages. Maybe useful as inspiration.

The key word is "plugins." GH Pages has some plugins and themes whitelisted, however I don't think I see any that are just a single include.

**Comment by m5o** [comment]
.

**Comment by allejo** [comment]
Based on my ignorant understanding of how Jekyll handles themes and plugins internally, I don't think it's possible. Jekyll probably never expected people to be crazy enough to write snippets in just liquid 😅

Anyhow, let's ping @oe and see if she has any time to join in this conversation. Otherwise, I think I'll lean towards closing this issue.

**Comment by oe** [comment]
You could try converting this from an include into a fully-fledged Liquid tag, a-la `{% toc html=content %}`. However, it looks like it'll be a bit of work. It's ultimately your decision, but if it works as an HTML file you can just drop into your project, I don't see the added value in publishing it to RubyGems.

**Comment by m5o** [comment]
The idea behind shipping this beauty as a RubyGem is the future maintenance and how easy updates can be published. Look how all jekyll themes, jekyll plugins etc are distributed this way 🚀
Nowadays no one wants to copy html files 🤓✌️

**Comment by allejo** [comment]
> You could try converting this from an include into a fully-fledged Liquid tag, a-la `{% toc html=content %}`.

The downside to this is that it'd become a plugin. The goal behind this project is to remain compatible with GH Pages and not require any whitelisting, hence it being crazily written in just Liquid 👍 

While pushing out updates would be far easier, the more I think about this, if this is distributed as a gem, then just use a proper plugin instead.

If something like [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme) got support to download arbitrary Liquid snippets, that'd be a different story. But I highly doubt people will become masochists and start writing snippets in Liquid for distribution.

**Comment by allejo** [comment]
And thanks for stopping by, @oe! I appreciate the company and your two cents
